\input texinfo
@setfilename include-value.info
@c 

@set testvar incl-incl.txi

@c test - in the variable name, and concatenation of text after.
@set test-var incl-incl.tx

@c test - in the variable name, and concatenation of text before and after.
@set test_var ncl-incl.tx


@node Top

testvar include: 
testvar verbatiminclude: @verbatiminclude @value{testvar}


test-var include: 
test-var verbatiminclude: @verbatiminclude @value{test-var}i


test_var include: 
test_var verbatiminclude: @verbatiminclude i@value{test_var}i


@bye
