\input texinfo @c -*-texinfo-*-
@setfilename def_end_of_line_footnote.info

@node Top
@top Test for end of line protected in definition commands in footnote


@footnote{
@deffn category deffn_name arguments arg2 @
   more {args @
  with end of line within} with 3 @@ @@@
 {one last arg}
deffn
@end deffn
}

@bye
