#!/bin/sh
# $Id: bootstrap,v 1.3 2003/11/06 22:56:48 karl Exp $
# Created 2003-08-29, Karl Berry.  Public domain.
# (Thanks to Akim Demaille.)

echo "Bootstrapping CVS Texinfo with:"

cmd="autoreconf --verbose --install --include=m4"
echo $cmd
$cmd

