#!/bin/sh
# $Id: bootstrap,v 1.10 2004/01/17 16:04:21 karl Exp $
# Created 2003-08-29, Karl Berry.  Public domain.

echo "Do not use Texinfo CVS from savannah, get it from berlios.de instead."
echo "I am waiting until cvs commit email is working again. --karl"
exit 1

echo "Bootstrapping CVS Texinfo with:"

# This overwrites lots of files with older versions.
# I keep the newest versions of files common between distributions up to
# date in CVS (see util/srclist.txt), because it's not trivial for every
# developer to do this.
#cmd="autoreconf --verbose --force --install --include=m4"

: ${AUTOHEADER=autoheader}
: ${AUTOMAKE=automake}
: ${AUTOCONF=autoconf}
: ${ACLOCAL=aclocal}

# So instead:
cmd="$AUTOHEADER && $ACLOCAL -I m4 && $AUTOMAKE && $AUTOCONF"
echo "  $cmd"
eval $cmd || exit 1

echo "Now run configure with your desired options, for instance:"
echo "  ./configure CFLAGS=-g --enable-maintainer-mode"
