
use strict;

$element_file_name = \&test_misc_file_name;

sub test_misc_file_name($$$)
{
  my $element = shift;
  my $type = shift;
  my $docu_name = shift;

  if ($type eq 'top' or (defined($element->{'doc_nr'}) and $element->{'doc_nr'} == 2))
  {
     my $extension = get_conf('EXTENSION');
     return "${docu_name}_abt"
      . ((defined($extension)) ? ".$extension" : '');
  }
  return undef;
}

1;
