#!/bin/sh
# $Id: accentenc,v 1.4 2010/12/04 00:05:53 karl Exp $
# Public domain.  Test encoded accent info output.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}
input=`basename $0`.txi
output=`basename $0`.info

# we expect two invalid encoded characters:
# accent-text.txi:45: warning: invalid encoded character `#156'.
# accent-text.txi:45: warning: invalid encoded character `#140'.
# These are oe and OE, and they are not supported in Latin 1.
../makeinfo --enable-encoding --no-split -I$srcdir $srcdir/$input 2>/dev/null
exit_status=$?
if test $exit_status = 0; then
  grep 'ì' $output >/dev/null \
  && grep 'ï' $output >/dev/null \
  && grep '/L' $output >/dev/null
  exit_status=$?
fi

rm -f $output

exit $exit_status
