#!/bin/sh
# $Id: defxcond,v 1.3 2010/12/04 00:05:53 karl Exp $
# Public domain.  Test conditionalized @deffnx.
# Report from: Akim Demaille, 14 Aug 2003 12:10:37 +0200.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

test=defxcond

../makeinfo -Dbar -o $test.out $srcdir/$test.txi || exit 1
grep ' -- bar:' $test.out >/dev/null || exit 2

../makeinfo -Ubar -o $test.out $srcdir/$test.txi || exit 3
grep ' -- bar:' $test.out >/dev/null && exit 4

rm -f $test.out
