#!/bin/sh
# Public domain.  Test @option inside @emph. 

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

../makeinfo --no-split --html -o emph-option.out $srcdir/emph-option.txi || exit 1
fgrep '<em>emphasized and referring to <samp></em>' emph-option.out && exit 3

rm -f emph-option.out
