#!/bin/sh
# $Id: html-title,v 1.2 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test that titles with @ commands don't produce markup
# in the <title>.  (And that the @ commands get expanded.)

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL

if ../makeinfo --no-split --html ${srcdir-.}/html-title.txi; then
  grep '^<title>@[^<>]*</title>$' html-title.html >/dev/null
  exit_status=$?
else
  exit_status=1
fi

rm -f html-title.html
exit $exit_status
