#!/bin/sh
# $Id: html-manuals,v 1.4 2010/12/04 00:05:53 karl Exp $
# Public domain.  Test that all the distribution manuals can be
# converted to HTML.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

for manual in info.texi info-stnd.texi texinfo.txi; do
  base=`echo $manual | sed 's/\.te*xi$//'`
  ../makeinfo --html -I$srcdir/../../doc -I../../doc --no-split \
              $srcdir/../../doc/$manual -o $base.html \
  || exit 1
  rm -f $base.html
done
