#!/bin/sh
# $Id: html-extrali,v 1.3 2010/12/04 00:05:53 karl Exp $
# Public domain.  Test no extra <li> from @menu.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

li_count=`../makeinfo --no-split --html -o - $srcdir/html-extrali.txi 2>/dev/null \
| grep -c '<li>'`

if test "$li_count" -ne 1; then
  echo "$li_count <li>s instead of one." >&2
  exit 1
else
  exit 0
fi
