#!/bin/sh
# $Id: include-value,v 1.5 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test @value expansion in @include and @verbatiminclude names.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

../makeinfo -I $srcdir $srcdir/include-value.txi
exit_status=$?

if test $exit_status = 0; then
  # should have three instances of _included_,
  # and three of {included}.
  count=`grep -c _included_ include-value.info`
  test $count = 3 || exit_status=`expr $exit_status + 1`

  count=`grep -c '{included}' include-value.info`
  test $count = 3 || exit_status=`expr $exit_status + 1`
fi

rm -f include-value.info
exit $exit_status
