#!/bin/sh
# $Id: include-value,v 1.1 2003/01/12 15:19:01 karl Exp $
# Test @value expansion in @include and @verbatiminclude names.

: ${srcdir=.}

../makeinfo $srcdir/include-value.txi
exit_status=$?

if test $exit_status = 0; then
  # should have three instances of _included_,
  # and three of {included}.
  count=`grep _included_ include-value.info | wc -l`
  test $count = 3 || exit_status=`expr $exit_status + 1`

  count=`grep '{included}' include-value.info | wc -l`
  test $count = 3 || exit_status=`expr $exit_status + 1`
fi

rm -f include-value.info
exit $exit_status
