#!/bin/sh
# $Id: macro-at,v 1.3 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test @@ in macro expansions, etc.  --eliz, 14nov99.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL

: ${srcdir=.}
../makeinfo $srcdir/macro-at.txi || exit 1

rm -f macro-at.info
