#!/bin/sh
# $Id: no-headers,v 1.5 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test that info.texi works with --no-headers (this
# includes node pointer defaulting).

# maybe need "nul" sometimes?  Not clear.
: ${nulldev=/dev/null}

unset TEXINFO_OUTPUT
: ${srcdir=.}
docdir=$srcdir/../../doc

../makeinfo --no-headers -o $nulldev -I$docdir info.texi
