#!/bin/sh
# $Id: node-value,v 1.3 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test @value expansion in node names.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

../makeinfo $srcdir/node-value.txi
grep -v "No Value" node-value.info >/dev/null
exit_status=$?

rm -f node-value.info
exit $exit_status
