#!/bin/sh
# $Id: node-expand,v 1.3 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test command expansion in node names.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

../makeinfo --commands-in-node-names $srcdir/node-expand.txi
test -s node-expand.info
exit_status=$?

rm -f node-expand.info
exit $exit_status
