#!/bin/sh
# $Id: node-whitespace,v 1.3 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test whitespace collapse in node names.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

../makeinfo $srcdir/node-whitespace.txi
test -s node-whitespace.info
exit_status=$?

rm -f node-whitespace.info
exit $exit_status
