#!/bin/sh
# $Id: quote-args,v 1.3 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test @quote-args facility.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

TMP=quote-args.out

cat > quote-args.samp <<EOT
*FIXME: Many arguments, separated by commas, are processed here*
natopocotuototam

EOT

../makeinfo --plaintex $srcdir/quote-args.txi | diff - quote-args.samp
exit_code=$?

rm quote-args.samp
exit $exit_code
