#!/bin/sh
# $Id: top2,v 1.2 2010/12/04 00:05:54 karl Exp $
# Public domain.  Test that a bare top node does not crash with --html.

unset TEXINFO_OUTPUT LANG LANGUAGE
LC_ALL=POSIX; export LC_ALL
: ${srcdir=.}

# But this input file is erroneous, so throw away errors.
../makeinfo --no-split --force -o top2.html --html $srcdir/top2.txi 2>/dev/null
test -s top2.html
exit_status=$?

rm -f top2.html
exit $exit_status
