\input texinfo @c -*-texinfo-*-

@setfilename multi_lang.info

@documentlanguage fr_NOWHERE

@node Top
@top Multi language file

This is in french

@menu
* chapter fr_NOWHERE::
* chapter ja::
* chapter en::
* chapter fr_FR::
* chapter de::
* chapter pt_BR::
@end menu

@node chapter fr_NOWHERE
@chapter Fr_NOWHERE

In french. @xref{Top}.

@menu
* sub fr_NOWHERE::
@end menu

@node sub fr_NOWHERE
@section fr_NOWHERE section

In fr section.

@documentlanguage ja
@node chapter ja
@chapter ja

In japanese. @xref{Top}.

@documentlanguage en
@node chapter en
@chapter en

In english. @xref{Top}.

@documentlanguage fr_FR
@node chapter fr_FR
@chapter fr_FR

@documentlanguage de
@node chapter de
@chapter de

@documentlanguage pt_BR
@node chapter pt_BR
@chapter pt_bR

In brazilian. @xref{Top}.


@bye

