\input texinfo @c -*-texinfo-*-

@setfilename test_menuentry.info

@node Top
@top test menu entry parsing

@menu
* (f)a1::
* (f)a2::  
* (f)a3::         d
* (f)a1c::@c c
* (f)a2c::  @c c
* (f)a3c::         d@c c
* (f) a4 ::   @c c
* (f)@@a@::: 
* a1:
* a2:  
* a1c:@c c
* a2c:  @c c
* a: (f)b
* a: (f)b@c c
* a: (f)b @c c
* a: (f)b1.c,
* a: (f)b2.c,     
* a: (f)b3.c,    d
* a: (f)b1c.c,@c c
* a: (f)b2c.c,     @c c
* a: (f)b3c.c,    d@c c
* a: (f)b1.. 
* a : (f) b2 ..
* a.n: (f)b3..         d
* a: (f)b1.c.
* a: (f)b2.c.  
* a: (f)b3.c. d
@end menu

@bye
