\input texinfo @c -*-texinfo-*-

@setfilename noindent_after_smallexample.info

@node Top
@top Element

You can obtain the newest version of @file{config.guess} and
@file{config.sub} from the CVS of the @samp{config} project at
@file{http://savannah.gnu.org/}. The commands to fetch them are
@smallexample
$ wget 'http://savannah.gnu.org/cgi-bin/viewcvs/config/config/config.guess?rev=HEAD&content-type=text/plain'
$ wget 'http://savannah.gnu.org/cgi-bin/viewcvs/config/config/config.sub?rev=HEAD&content-type=text/plain'
@end smallexample
@noindent
Less recent versions are also contained in the GNU @code{automake} and
GNU @code{libtool} packages.

@bye
