\input texinfo.tex    @c -*-texinfo-*-

@setfilename float.info

@node Top
@top Test floats

A list of floats at the begining.
@listoffloats Text

After the listoffloats.

@menu
* chapter::
* Unnumbered::
* Chapter with unnumbsubsec::
* list of floats::
@end menu

@float Text, text with a lot of features
An example of float @enddots{}

@c makeinfo --docbook segfaults
An example.
@example 
example
@end example

A multitable.
@multitable {truc} {bidule}
@item truc @tab bidule
@item truc @tab bidule
@end multitable

An index entry
@cindex float example

A table.
@table @emph
@item truc 
line
@end table

An itemize.
@itemize @minus
@item truc 
line
@end itemize

A ref.
@xref{Top,xref Text with features}.
A footnote.
@footnote{footnote Text with features}.

@TeX{} and @emph{@b{t@'e@^{@dotless{i}}}@url{an_url}} @sc{and} @verb{!it is @verb!} @ a wo@-rd @!@@ @AE{}.

@caption{ An example of float caption@enddots{}
An example.
@example 
example
@end example

A table.
@table @emph
@item truc 
line
@end table

A multitable.
@multitable {truc} {bidule}
@item truc @tab bidule
@item truc @tab bidule
@end multitable
An index entry
@cindex float example in caption

An itemize.
@itemize @minus
@item truc 
line
@end itemize

A ref.
@xref{Top,xref Text with features caption}.
A footnote.
@footnote{footnote Text with features caption}.

@TeX{} and @emph{@b{t@'e@^{@dotless{i}}}@url{an_url}} @sc{and} @verb{!it is @verb!} @ a wo@-rd @!@@ @AE{}.
}

@shortcaption{@TeX{} and @emph{@b{t@'e@^{@dotless{i}}}@url{an_url}} @sc{and} @verb{!it is @verb!} @ a wo@-rd @!@@ @AE{}.}

@end float


@float Text
No label but caption and shortcaption.

@caption{No label}
@shortcaption{No label}
@end float

@float ,label but no type
No type but caption and shortcaption.

@caption{No type}
@shortcaption{No type}
@end float


@float ,label but no type and no caption
No type but label and no caption nor shortcaption.
                                                                                
@end float


@float
No label, no type, no caption no shortcaption.

@end float

@float
No label, no type, but caption and shortcaption.
@caption{No label, no type, but caption and shortcaption.}
@shortcaption{No label, no type, but caption and shortcaption.}
@end float



@float ,label but no type 2
Second float with no type.

@caption{No type 2}
@shortcaption{No type 2}
@end float

@float Warning, warning in top
A warning

@caption{A warning}
@shortcaption{A warning}
@end float

@node chapter
@chapter A chapter

@float Text, text in chapter
Text in chapter

@caption{Text in chapter}
@end float

@float th@'eor@`eme, theoreme
A th@'eor@`eme

@caption{A th@'eor@`eme}
@end float

@float ,label but no type in chapter
float with no type.

@caption{No type in chapter}
@shortcaption{No type in chapter}
@end float

@float Warning, warning in chapter
A warning

@caption{A warning in chapter}
@shortcaption{A warning in chapter}
@end float

@menu
* section::
@end menu

@node section
@section A section

@float Text, text in section

A text in float no caption a label a type.

@end float

@node Unnumbered
@unnumbered Unnumbered

@menu
* Section within unnumbered::
@end menu
@float Text, unnumbered float
unnum
@shortcaption{unnumbered float}
@caption{unnumbered float}
@end float

@float ,label but no type in unnumbered
float with no type.

@caption{No type in unnumbered}
@shortcaption{No type in unnumbered}
@end float


@node Section within unnumbered
@section Section within unnumbered


@float Text, Section within unnumbered float
Section within unnumbered
@shortcaption{Section within unnumbered}
@caption{Section within unnumbered}
@end float

@node Chapter with unnumbsubsec
@chapter Chapter with unnumbsubsec

@menu
* unnumbered sec::
@end menu
@float Text, Chapter with subsec float
Chap
@shortcaption{Chapter with subsec}
@caption{Chapter with subsec}
@end float

@node unnumbered sec
@unnumberedsec unnumbered sec

@float Text, unnumbered sec float
Chap
@shortcaption{unnumbered sec float}
@caption{unnumbered sec float}
@end float

@float ,label but no type in unnumbered subsec in chapter
float with no type.

@caption{No type in unnumbered subsec in chapter}
@shortcaption{No type in unnumbered subsec in chapter}
@end float

@node list of floats
@unnumbered list of floats

See @ref{text in section}.
And (@pxref{text in chapter}).
@xref{text with a lot of features}.

And now a ref (without manual or printed manual) 
@ref{text with a lot of features, cross ref, title}.

And now a ref (with manual without printed manual) 
@ref{text with a lot of features, cross ref, title, manual}.

And now a ref (without manual with a printed manual) 
@ref{text with a lot of features, cross ref, title,, printed manual title}.

A ref to float without type @ref{label but no type}.

@listoffloats Text
@listoffloats th@'eor@`eme

@printindex cp

@bye
