@c
@c This file is part of the ``Texinfo to HTML Converter'' manual
@c which is part of the ``texi2html'' distribution.
@c
@c License:
@c    Copyright (C) 1999, 2000  Free Software Foundation, Inc.
@c
@c    This program is free software; you can redistribute it
@c    and/or modify it under the terms of the GNU General Public
@c    License as published by the Free Software Foundation;
@c    either version 2 of the License, or (at your option) any
@c    later version.
@c
@c    This program is distributed in the hope that it will be
@c    useful, but WITHOUT ANY WARRANTY; without even the implied
@c    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
@c    PURPOSE.  See the GNU General Public License for more
@c    details.
@c
@c    You should have received a copy of the GNU General
@c    Public License along with this program; if not, write to
@c    the Free Software Foundation, Inc., 59 Temple Place, Suite
@c    330, Boston, MA  02111-1307  USA
@c
@c
@c Revisions:
@c $Id: custpage.texi,v 1.1.1.1 2001/04/29 07:23:18 dprice Exp $
@c
@c Author:
@c   Karl Heinz Marbaise <khmarbaise@gmx.de>
@c
@c Description:
@c   Here are the informations about customizing page
@c   layout.
@c
@c ========================================================
@chapter Customizing page layout
This chapter is designed to help you to change the
complete layout of the @acronym{HTML} output if you like to
do so.


a) General: Philosphy, and how it works@*
aa) Navigation panels@*
b) Top page@*
c) Section pages@*




@menu
* TipsNewDesign::           .
* CustPagePhil::            .
* CustPageTopPage::         .
* CustPageSectionPages::    .
* CustPageMiscPage::        .
@end menu
@c --------------------------------------------------------
@node TipsNewDesign
@section Tips how to create a new site design

Here you can find information how you should work to pick
up a new design with @command{texi2html}.


@c --------------------------------------------------------
@node CustPagePhil
@section Page Layout and the philosophy

@menu
* CustPagePhilNav:: Navigation panels.
@end menu
@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustPagePhilNav
@subsection Navigation panels

Head and foot Navigation panels.

@c --------------------------------------------------------
@node CustPageTopPage
@section Top Page
@c --------------------------------------------------------
@node CustPageSectionPages
@section Section Pages
@c --------------------------------------------------------
@node CustPageMiscPage
@section Misc pages
Here you can find information about the creation of the
@dfn{ToC} (@i{Table Of content}), About---Page
etc. and specialy how to change them to get your own
design.

@acronym{ToC} @code{T2H_DEFAULT_print_toc_frame} in
@file{texi2html.init}

@menu
* CustPagePageHeadToc:: .
* CustPagePageHead::    .
* CustPagePageFoot::    .
@end menu

@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustPagePageHeadToc,,,CustPageMiscPage
@subsection Table Of Contents

The following code is the original code out of the
initialization file (@pxref{InitFile,Initialization file}).

@example
sub T2H_DEFAULT_print_toc_frame
@{
  my $fh = shift;
  &$T2H_print_page_head($fh);
  print $fh <<EOT;
<H2>Content</H2>
EOT
  print $fh map @{s/HREF=/target=\"main\" HREF=/; $_;@} @@stoc_lines;
  print $fh "</BODY></HTML>\n";
@}
@end example

As you can see it is very simple Perl Code, which can
be changed more or less simple to fit you requirements
(@pxref{CustPagePageHead,,T2H_DEFAULT_print_page_head}).


@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustPagePageHead,,,CustPageMiscPage
@subsection Page header
Page Head @code{T2H_DEFAULT_print_page_head}

@c references on T2H_DOCTYPE
@c               T2H_AUTHORS
@example
sub T2H_DEFAULT_print_page_head
@{
  my $fh = shift; 
  my $longtitle = "$T2H_THISDOC@{title@}: $T2H_NAME@{This@}";
  print $fh <<EOT;
<HTML>
$T2H_DOCTYPE
<!-- Created on $T2H_TODAY by $THISPROG -->
<!-- 
$T2H_AUTHORS 
-->
<HEAD>
<TITLE>$longtitle</TITLE>

<META NAME="description" CONTENT="$longtitle">
<META NAME="keywords" CONTENT="$longtitle">
<META NAME="resource-type" CONTENT="document">
<META NAME="distribution" CONTENT="global">
<META NAME="Generator" CONTENT="$THISPROG">
$T2H_EXTRA_HEAD
</HEAD>

<BODY $T2H_BODYTEXT>
$T2H_AFTER_BODY_OPEN
EOT
@}
@end example

@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustPagePageFoot,,,CustPageMiscPage
@subsection Page footer

Page Foot @code{T2H_DEFAULT_print_page_foot}
