@c
@c This file is part of the ``Texinfo to HTML Converter'' manual
@c which is part of the ``texi2html'' distribution.
@c
@c License:
@c    Copyright (C) 1999, 2000  Free Software Foundation, Inc.
@c
@c    This program is free software; you can redistribute it
@c    and/or modify it under the terms of the GNU General Public
@c    License as published by the Free Software Foundation;
@c    either version 2 of the License, or (at your option) any
@c    later version.
@c
@c    This program is distributed in the hope that it will be
@c    useful, but WITHOUT ANY WARRANTY; without even the implied
@c    warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
@c    PURPOSE.  See the GNU General Public License for more
@c    details.
@c
@c    You should have received a copy of the GNU General
@c    Public License along with this program; if not, write to
@c    the Free Software Foundation, Inc., 59 Temple Place, Suite
@c    330, Boston, MA  02111-1307  USA
@c
@c
@c Revisions:
@c $Id: custhtml.texi,v 1.1 2001/04/29 07:23:18 dprice Exp $
@c
@c Author:
@c   Karl Heinz Marbaise <khmarbaise@gmx.de>
@c
@c Description:
@c   Here are the informations about customizing HTML
@c   BODY, PRE- and AFTER Body.
@c
@c ========================================================
@chapter Customizing HTML
If you like to read the following section, it is assumed
you are famillar with @acronym{HTML}. If not, you shouldn't
read this, cause you don't know what we are talking about.

Here you can find information how to change the
@acronym{HTML} parts of a document. These are the
header, body etc.

These are the defaults which are
part of the distribution as @file{texi2html.init}.


How to do changes of the customization...
needed steps.
@c examples.

@menu
* CustHTMLBody::      Customizing BODY Text.
* CustHTMLHead::      Customizing Head.
@end menu
@c --------------------------------------------------------
@node CustHTMLBody,,,CustHTML
@section Body

@menu
* CustHTMLBodyText::    Body Text.
* CustHTMLPreBodyText:: PRE Body Text.
* CustHTMLAfterBody::   After Body Text.
@end menu
@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustHTMLBodyText
@subsection Body Text


@vindex T2H_BODYTEXT

@example
$T2H_BODYTEXT =
    . 'LANG="' . $T2H_LANG . '" BGCOLOR="#FFFFFF" '
    . 'TEXT="#000000" LINK="#0000FF" '
    . 'VLINK="#800080" ALINK="#FF0000"';
@end example

If you like to change the basic color combination, you can
change the entry @var{T2H_BODYTEXT}.

@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustHTMLPreBodyText
@subsection Body Text
@c -=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=-=
@node CustHTMLAfterBody
@subsection After Body Text

@vindex T2H_AFTER_BODY_OPEN
@vindex T2H_PRE_BODY_CLOSE

@vindex T2H_EXTRA_HEAD

@example
# text inserted after <BODY ...>
$T2H_AFTER_BODY_OPEN = '';

#text inserted before </BODY>
$T2H_PRE_BODY_CLOSE = '';

# this is used in footer
$T2H_ADDRESS = "by <I>$T2H_USER</I> " if $T2H_USER;
$T2H_ADDRESS .= "on <I>$T2H_TODAY</I>";

# this is added inside <HEAD></HEAD> after <TITLE> and some META NAME stuff
# can be used for <style> <script>, <meta> tags
$T2H_EXTRA_HEAD = '';
@end example

The default output into the @acronym{HTML} file.
@xref{OptionDocType}.


The following code is produced by
@code{T2H_DEFAULT_print_page_head}.

Detailed information can be found at
@ref{CustPagePageHead}.

@example
@include custhtml-header.htmltexi
@end example

@c --------------------------------------------------------
@node CustHTMLHead,,,CustHTML
@section Head
