#!/bin/sh
# $Id: srclist-update,v 1.3 2002/09/06 13:25:31 karl Exp $

destdir=${1-/u/texinfo/src}
cd $destdir || exit 1

verbose=false
#chicken="echo (would)"

srctmp=${TMPDIR-/tmp}/srclist.src
dsttmp=${TMPDIR-/tmp}/srclist.dst

: ${EMACSSRC=$HOME/gnu/src/emacs}
: ${GETTEXT=/usr/local/gnu/share/gettext}
: ${GNULIBSRC=$HOME/gnu/src/gnulib}
: ${GNUBIN=/usr/local/gnu/bin}
: ${TEXMF=/usr/local/texmf/texmf}

cat | while read src dst; do
  test -z "$dst" && continue  # skip lines without second element
  echo "$src $dst" | sed 's/#.*$//' | egrep '^\s*$' >/dev/null \
  && continue  # skip whitespace and comment-only lines
  
  src=`eval echo $src`
  if test ! -r $src; then
    echo "$0: cannot read $src" >&2
    continue
  fi
  
  # If given src/foo.c dst, copy to dst/foo.c.
  dst=`eval echo $dst`
  test -d $dst && dst=$dst/`basename $src`
  
  # $ Id: lines will differ.
  fgrep -v '$'"Id:" $src >$srctmp
  test -r $dst && fgrep -v '$'"Id:" $dst >$dsttmp

  if test ! -e $dst; then
    echo "$src -> $dst (new)"
    $chicken cp -p $src $dst
  elif cmp -s $srctmp $dsttmp; then
    $verbose && echo "$src -> $dst (unchanged)"
  else
    echo "$src -> $dst (changes)"
    diff -c2 $src $dst
  fi
done

rm -f $srctmp $dsttmp
