#! /bin/sh

if [ z"$srcdir" = 'z' ]; then
  srcdir=.
fi

"$srcdir"/tests.sh all \
 macros sectioning coverage formatting info_coverage encodings indices \
 layout nested_formats contents \
 htmlxref htmlxref-only_mono htmlxref-only_split invalid
