\input texinfo @c -*-texinfo-*-

@setfilename center.info

@node Top
@top Test @@center

A center @center Centered line
And a center after empty line

@center centered line after empty line

And a center at end of line @center
And an empty center @center   

@center @ref{Top}

@center @ref{Top, ,title
very long}

@center Centered text with a footnote@footnote{This footnote
shows an important feature of the centered text.

@example
@table
@item item
line
@end table 
@end example} and text after the footnote.

center in a @@code:

@code{@center Centered code line}

@table
@item @center centered text in item
table line @center centered text in table line
@center centered line with item @item second item on center line
@end table

@center unclosed command on center line @code{in code
Still in code}

@center unclosed command on center line with paragraph @code{in code

Still in code after paragraph}

@center unclosed command on center line with other center @code{in code
@center still in code on center line}. After code.

@center unclosed command on center line with other center and paragraph @code{in code

@center still in code on center line}. After code.

@samp{begin samp @center center and end samp} after end of samp

Empty double center:
@center @center

@center after first center @center after second center

@center @samp{something @center end of samp}

@center after first center @samp{@center after second center

End of samp}

@unnumbered Heading

@multitable {AAA}  {BBB}
@item truc @tab bidule
@center @item ctruc @tab cbidule
@center @item cstruc
@end multitable

@center before the table @table
@item item in center
Line in center
@item second item
@end table

@bye
