\input texinfo @c -*-texinfo-*-
@setfilename comments.info

@hyphenation{some-where 
be-low   
  may-be to-morow 


 }

@node Top
@top
@subheading Comment like:

Text line followed by a comment on the same line and another below @c comment
@c comment
Text line after the comment followed by a comment @comment c
Text line after the text line followed by the comment.

Comment at the end of the line @c comment

Example with comments 2 lines
@example 
line @c comment
second line @c comment
@end example

Example with comments 1 line
@example
line @c comment
@end example

No comments
@example
line 
@end example

The same but with oddfooting instead of comment:
Text line followed by a comment on the same line and another below @oddfooting comment
@oddfooting some text ignored
Text line after the comment followed by a comment @oddfooting c
Text line after the text line followed by the comment.

@@pagesizes @pagesizes 200mm,150mm following @@pagesizes arg
@@afourpaper @afourpaper on line following afourpaper
@@smallbook @smallbook on line following smallbook
@@headings @headings on line following headings
@@oddfooting @oddfooting on line following oddfooting
@@everyheading @everyheading on line following everyheading
@@everyfooting @everyfooting on line following everyfooting
@@evenheading @evenheading on line following evenheading
@@evenfooting @evenfooting on line following evenfooting
@@oddheading @oddheading on line following 
@ifnottex
@@need @need 0.1 on line following
@end ifnottex
@@need @need 0.1 
@@setchapternewpage @setchapternewpage on line following setchapternewpage
@@raisesections @raisesections on line following raisesections
@@lowersections @lowersections on line following lowersections
@c @@kbdinputstyle @kbdinputstyle wrong arg on line following kbdinputstyle
@ifnottex
@@kbdinputstyle code @kbdinputstyle code something
@end ifnottex
@@afourpaper @afourpaper on line following afourpaper
@@afourlatex @afourlatex on line following afourlatex
@@afourwide @afourwide on line following afourwide

@c tex error: Use of \ doesn't match its definition.
@ifnottex
@@definfoenclose phoo,//,\\  @definfoenclose phoo,//,\\

@phoo{bar}
@end ifnottex

@@definfoenclose phi,:,:  @definfoenclose phi,:,:

@c this is required
@iftex
@global@let@phi=@i
@end iftex

@phi{bar}

@strong{very strong}

@definfoenclose strong,(strong:,:)

@strong{ is it really strong? }

Makeinfo ignore @@kbdinputstyle:

@kbdinputstyle code

@kbd{truc}

@example
@kbd{example}
@end example

@subheading ignore arg


Commands doesn't accept anything after a non numerical arg on the line
and ignore things after a numerical arg

@@paragraphindent asis @paragraphindent asis
@@paragraphindent 0 @paragraphindent 0
@@paragraphindent none @paragraphindent none
@@paragraphindent 4 @paragraphindent 4
@@firstparagraphindent none @firstparagraphindent none
@ifnottex
@@exampleindent 6 @exampleindent 6 on line following exampleindent
@end ifnottex
@@exampleindent 6 @exampleindent 6 
@@footnotestyle @footnotestyle end 
@@footnotestyle @footnotestyle separate 

Special arg for documentencoding. makeinfo complains, not tex

@documentencoding
@@documentencoding @documentencoding bad encoding name
@documentencoding ISO-8859-1
@c accepts on or off
@@frenchspacing @frenchspacing on
@@frenchspacing @frenchspacing off
@c accepts 10 or 11
@@fonttextsize @fonttextsize 10
@c @@fonttextsize @fonttextsize 11
@c accept false or true
@c makeinfo don't care about the arg and remove the remainiing of the line
@allowcodebreaks false
@code{false aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}

@allowcodebreaks true
@code{true aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa-aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}

@ignore
@@ @ on line following 
@@ @ on line following 
@@ @ on line following 
@@ @ on line following 
@end ignore

@subheading command removed

And now finalout:
Text line followed by finalout on the same line and another below @finalout
@finalout
Text line after the finalout followed by a fianlout @finalout
Text line after the text line followed by the finalout.

Test text after finalout
@finalout a word after finalout
Line after finalout

@@page @page @@noindent @noindent @@refill @refill something

@noindent     noindent at beginning of line
@noindent  
noindent on the preceding line
  @noindent    noindent after space at beginning of line
@page         page at beginning of line
@page
After page on it's own line.

@@page @page   @@noindent @noindent    @@refill @refill @@novalidate @novalidate something

@@contents @contents something

@ignore
@@ @ arg
@@ @ arg
@@ @ arg
@@ @ arg
@end ignore

@subheading special

Only valid between iftex:
@c @@vskip @vskip @@cropmarks @cropmarks
Unknown ???
@c @@fillbreak  @fillbreak eol

@@exdent @exdent line after exdent

And now sp:
Text line followed by a comment on the same line and another below @sp 1
@sp 2
Text line after the comment followed by a comment @sp 1
Text line after the text line followed by the comment.
@ifnottex
@sp 2 a number after sp
@end ifnottex

Menu:
@menu
* node::
* bidule::
* bidule2::
* undefined::
@end menu

@node node
@chapter chapter
@menu
* truc::
@end menu

@node truc
@section section

first @@contents @contents line following first content
second @@contents @contents line following second content
Third content on the following line on his own
@contents
Line following contents

@node bidule
@chapter bidule

@@shortcontents @shortcontents eol
@@shortcontents @shortcontents eol
@@summarycontents @summarycontents line following summarycontents

@node bidule2
@chapter last

@c no ref ignored because of novalidate
@ref{machin}

@bye
