\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename menus.info

@node Top
@top Top

@menu
* chapter::               chapter

Menu comment

* chapter2:description.   Chapter 2
@detailmenu
* s--ect@comma{}ion:: s--ect@comma{}ion

Menu comment
``simple-double--three---four----''@*

* subsection:: 
* subsubsection::
@end detailmenu

Other comment

* chapter3::
@detailmenu
* s--ect@comma{}ion:: s--ect@comma{}ion

Menu comment
``simple-double--three---four----''@*

* subsection:: 
* subsubsection::
@end detailmenu
* chapter4::
@end menu

@node chapter
@chapter chapter

@menu 
* s--ect@comma{}ion:: s--ect@comma{}ion
* subsubsection::
@end menu

@node s--ect@comma{}ion
@section A section

@menu
* subsection:: 
@end menu

@node subsection
@subsection subsection

@menu
* subsubsection::
@end menu

@node subsubsection
@subsubsection subsubsection

@node chapter2
@chapter chapter 2

@node chapter3
@chapter chapter 3

@node chapter4
@chapter chapter 4

@contents
@shortcontents

@bye
