\input texinfo @c -*-texinfo-*-
@setfilename formatting.info
@node Top
@top Top section

@menu
* chapter::               chapter

Menu comment

* chapter2:description.   Chapter 2
@end menu

@macro mymacro

<
>
"
&

``simple-double--three---four----''@*
code: @code{``simple-double--three---four----''} @*
asis: @asis{``simple-double--three---four----''} @*
strong: @strong{``simple-double--three---four----''} @*
kbd: @kbd{``simple-double--three---four----''} @*

@cindex --option
@cindex ``
@findex ``
@findex --foption

@"u 
@"{U} 
@~n
@^a
@'e
@=o
@`i
@'{@dotless{i}} 

@dotless{truc}
@dotless{i}

@*
@@ followed by a space
@ 
@@ followed by a tab
@	
@@ followed by a new line
@
@-
@|
@:
@!
@?
@.
@@
@}
@{
@/


@TeX{}
@c @br{}
@bullet{}
@copyright{}
@dots{}
@enddots{}
@equiv{}
@error{}
@expansion{}
@minus{}
@point{}
@print{}
@result{}
@today{}
@aa{}
@AA{}
@ae{}
@oe{}
@AE{}
@OE{}
@o{}
@O{}
@ss{}
@l{}
@L{}
@exclamdown{}
@questiondown{}
@pounds{}

@acronym{--a}
@asis{--a}
@b{--a}
@cite{--a}
@code{--a}
@command{--a}
@ctrl{--a}
@dfn{--a}
@dmn{--a}
@email{--a,--b}
@email{,--b}
@email{--a}
@emph{--a}
@env{--a}
@file{--a}
@i{--a}
@kbd{--a}
@key{--a}
@math{--a}
@option{--a}
@r{--a}
@samp{--a}
@sc{--a}
@strong{--a}
@t{--a}
@titlefont{--a}
@uref{--a,--b}
@uref{--a}
@uref{,--b}
@url{--a,--b}
@url{--a,}
@url{,--b}
@var{--a}
@verb{:--a:}
@w{--a}
@H{a}
@H{--a}
@dotaccent{a}
@dotaccent{--a}
@ringaccent{a}
@ringaccent{--a}
@tieaccent{a}
@tieaccent{--a}
@u{a}
@u{--a}
@ubaraccent{a}
@ubaraccent{--a}
@udotaccent{a}
@udotaccent{--a}
@v{a}
@v{--a}
@,{c}
@,{--c}
@dotless{--a}
@dotless{a}
@footnote{in footnote}
@footnote{in footnote2}

@image{f--ile,,e--xt}
@image{f--ile}
@image{,,e--xt}
@image{,,,e--xt}


@quotation
a q--uotation
@end quotation

@itemize
@item i--temize
@end itemize

@itemize +
@item i--tem +
@end itemize

@itemize @bullet
@item b--ullet
@end itemize

@itemize @emph
@item e--mph item
@end itemize

@itemize @emph after emph
@item e--mph item
@end itemize

@itemize @bullet a--n itemize line
@item i--tem 1
@item i--tem 2
@end itemize

@enumerate
@item e--numerate
@end enumerate

@multitable @columnfractions 6 7
@item mu--ltitable item @tab multitable tab
@end multitable

@example
e--xample
@end example

@smallexample
s--mallexample
@end smallexample

@display 
d--isplay
@end display

@smalldisplay
s--malldisplay
@end smalldisplay

@lisp
l--isp
@end lisp

@smalllisp
s--malllisp
@end smalllisp

@format
f--ormat
@end format

@smallformat
s--mallformat
@end smallformat

@deffn c--ategory d--effn_name a--rguments...
d--effn
@end deffn

@deffn cate--gory de--ffn_name ar--guments...
def--fn
@end deffn

@defvr c--ategory d--efvr_name
d--efvr
@end defvr

@deftypefn c--ategory t--ype d--eftypefn_name a--rguments...
d--eftypefn
@end deftypefn

@deftypeop c--ategory c--lass t--ype d--eftypeop_name a--rguments...
d--eftypeop
@end deftypeop

@deftypevr c--ategory t--ype d--eftypevr_name
d--eftypevr
@end deftypevr

@defcv c--ategory c--lass d--efcv_name
d--efcv
@end defcv

@defop c--ategory c--lass d--efop_name a--rguments...
d--efop
@end defop

@deftp c--ategory d--eftp_name a--ttributes...
d--eftp
@end deftp

@defun d--efun_name a--rguments...
d--efun
@end defun

@defmac d--efmac_name a--rguments...
d--efmac
@end defmac

@defspec d--efspec_name a--rguments...
d--efspec
@end defspec

@defvar d--efvar_name
d--efvar
@end defvar

@defopt d--efopt_name
d--efopt
@end defopt

@deftypefun t--ype d--eftypefun_name a--rguments...
d--eftypefun
@end deftypefun

@deftypevar t--ype d--eftypevar_name
d--eftypevar
@end deftypevar

@defivar c--lass d--efivar_name
d--efivar
@end defivar

@deftypeivar c--lass t--ype d--eftypeivar_name
d--eftypeivar
@end deftypeivar

@defmethod c--lass d--efmethod_name a--rguments...
d--efmethod
@end defmethod

@deftypemethod c--lass t--ype d--eftypemethod_name a--rguments...
d--eftypemethod
@end deftypemethod

@xref{chapter, cross ref name, title, file name, manual}
@ref{chapter, cross ref name, title, file name, manual}
@pxref{chapter, cross ref name, title, file name, manual}
@inforef{chapter, cross ref name, file name}

@ref{chapter}
@ref{node}
@ref{,cross ref name}
@ref{,,title}
@ref{,,,file name}
@ref{,,,,manual}
@ref{chapter,cross ref name}
@ref{chapter,,title}
@ref{chapter,,,file name}
@ref{chapter,,,,manual}
@ref{node,cross ref name}
@ref{node,,title}
@ref{node,,,file name}
@ref{node,,,,manual}
@ref{chapter,cross ref name,title,}
@ref{chapter,cross ref name,,file name}
@ref{chapter,cross ref name,,,manual}
@ref{node,cross ref name,title,}
@ref{node,cross ref name,,file name}
@ref{node,cross ref name,,,manual}
@ref{chapter,cross ref name,title,file name}
@ref{chapter,cross ref name,title,,manual}
@ref{node,cross ref name,title,file name}
@ref{node,cross ref name,title,,manual}
@ref{chapter,cross ref name,title, file name, manual}
@ref{node,cross ref name,title, file name, manual}
@ref{chapter,,title,file name}
@ref{chapter,,title,,manual}
@ref{node,,title,file name}
@ref{node,,title,,manual}
@ref{chapter,,title, file name, manual}
@ref{node,,title, file name, manual}
@ref{chapter,,,file name,manual}
@ref{node,,,file name,manual}
@ref{,cross ref name,title,}
@ref{,cross ref name,,file name}
@ref{,cross ref name,,,manual}
@ref{,cross ref name,title,file name}
@ref{,cross ref name,title,,manual}
@ref{,cross ref name,title, file name, manual}
@ref{,,title,file name}
@ref{,,title,,manual}
@ref{,,title, file name, manual}
@ref{,,,file name,manual}

@inforef{chapter, cross ref name, file name}
@inforef{chapter}
@inforef{chapter, cross ref name}
@inforef{chapter,,file name}
@inforef{node, cross ref name, file name}
@inforef{node}
@inforef{node, cross ref name}
@inforef{node,,file name}
@inforef{,cross ref name }
@inforef{,,file name}
@inforef{,cross ref name, file name}

@table @bullet
@item a
l--ine
@end table

@vtable @asis
@item a
l--ine
@end vtable

@ftable @minus
@item a
l--ine
@end ftable


@end macro

@copying
@mymacro{}
@end copying

@mymacro{}

@example
@mymacro{}
@end example

@cindex t--ruc
@cindex T--ruc
@cindex .
@cindex ?
@cindex a
@findex t--ruc
@findex T--ruc
@findex .
@findex ?
@findex a


cp
@printindex cp

fn
@printindex fn

vr
@printindex vr

ky
@printindex ky

pg
@printindex pg

tp
@printindex tp



@node chapter
@chapter chapter

@footnote{in footnote}

@format
@menu 
* s--ection:: s--ection

Menu comment
``simple-double--three---four----''@*

@end menu
@end format

@node s--ection
@section A section

@menu
* subsection:: 
@end menu

@node subsection
@subsection subsection

@menu
* subsubsection::
@end menu

@anchor{anchor}

@node subsubsection
@subsubsection subsubsection

@node chapter2
@chapter chapter 2

@printindex cp
@printindex fn

@contents
@shortcontents
