\input texinfo @c -*-texinfo-*-
@setfilename formatting.info
@node Top
@top Top section

@menu
* chapter::               chapter

Menu comment

* chapter2:description.   Chapter 2
@end menu

@macro mymacro

<
>
"
&

``simple-double--three---four----''@*
code: @code{``simple-double--three---four----''} @*
asis: @asis{``simple-double--three---four----''} @*
strong: @strong{``simple-double--three---four----''} @*
kbd: @kbd{``simple-double--three---four----''} @*

@cindex --option
@cindex ``
@findex ``
@findex --foption

@"u 
@"{U} 
@~n
@^a
@'e
@=o
@`i
@'{@dotless{i}} 

@dotless{truc}
@dotless{i}

@*
@@ followed by a space
@ 
@@ followed by a tab
@	
@@ followed by a new line
@
@-
@|
@:
@!
@?
@.
@@
@}
@{
@/


@TeX{}
@c @br{}
@bullet{}
@copyright{}
@dots{}
@enddots{}
@equiv{}
@error{}
@expansion{}
@minus{}
@point{}
@print{}
@result{}
@today{}
@aa{}
@AA{}
@ae{}
@oe{}
@AE{}
@OE{}
@o{}
@O{}
@ss{}
@l{}
@L{}
@exclamdown{}
@questiondown{}
@pounds{}

@acronym{a}
@asis{a}
@b{a}
@cite{a}
@code{a}
@command{a}
@ctrl{a}
@dfn{a}
@dmn{a}
@email{a,b}
@email{,b}
@email{a}
@emph{a}
@env{a}
@file{a}
@i{a}
@kbd{a}
@key{a}
@math{a}
@option{a}
@r{a}
@samp{a}
@sc{a}
@strong{a}
@t{a}
@titlefont{a}
@uref{a,b}
@uref{a}
@uref{,b}
@url{a,b}
@url{a,}
@url{,b}
@var{a}
@verb{:a:}
@w{a}
@H{a}
@dotaccent{a}
@ringaccent{a}
@tieaccent{a}
@u{a}
@ubaraccent{a}
@udotaccent{a}
@v{a}
@,{a}
@c @m_cedilla{a}
@dotless{a}
@footnote{in footnote}
@footnote{in footnote2}

@image{file,,ext}
@image{file}
@image{,,ext}
@image{,,,ext}


@quotation
a quotation
@end quotation

@itemize
@item itemize
@end itemize

@itemize +
@item item +
@end itemize

@itemize @bullet
@item bullet
@end itemize

@itemize @emph
@item emph item
@end itemize

@itemize @emph after emph
@item emph item
@end itemize

@itemize @bullet an itemize line
@item item 1
@item item 2
@end itemize

@enumerate
@item enumerate
@end enumerate

@multitable @columnfractions 6 7
@item multitable item @tab multitable tab
@end multitable

@example
example
@end example

@smallexample
smallexample
@end smallexample

@display 
display
@end display

@smalldisplay
smalldisplay
@end smalldisplay

@lisp
lisp
@end lisp

@smalllisp
smalllisp
@end smalllisp

@format
format
@end format

@smallformat
smallformat
@end smallformat

@deffn category deffn_name arguments...
deffn
@end deffn

@deffn cate--gory de--ffn_name ar--guments...
def--fn
@end deffn

@defvr category defvr_name
defvr
@end defvr

@deftypefn category type deftypefn_name arguments...
deftypefn
@end deftypefn

@deftypeop category class type deftypeop_name arguments...
deftypeop
@end deftypeop

@deftypevr category type deftypevr_name
deftypevr
@end deftypevr

@defcv category class defcv_name
defcv
@end defcv

@defop category class defop_name arguments...
defop
@end defop

@deftp category deftp_name attributes...
deftp
@end deftp

@defun defun_name arguments...
defun
@end defun

@defmac defmac_name arguments...
defmac
@end defmac

@defspec defspec_name arguments...
defspec
@end defspec

@defvar defvar_name
defvar
@end defvar

@defopt defopt_name
defopt
@end defopt

@deftypefun type deftypefun_name arguments...
deftypefun
@end deftypefun

@deftypevar type deftypevar_name
deftypevar
@end deftypevar

@defivar class defivar_name
defivar
@end defivar

@deftypeivar class type deftypeivar_name
deftypeivar
@end deftypeivar

@defmethod class defmethod_name arguments...
defmethod
@end defmethod

@deftypemethod class type deftypemethod_name arguments...
deftypemethod
@end deftypemethod

@xref{chapter, cross ref name, title, file name, manual}
@ref{chapter, cross ref name, title, file name, manual}
@pxref{chapter, cross ref name, title, file name, manual}
@inforef{chapter, cross ref name, file name}

@ref{chapter}
@ref{node}
@ref{,cross ref name}
@ref{,,title}
@ref{,,,file name}
@ref{,,,,manual}
@ref{chapter,cross ref name}
@ref{chapter,,title}
@ref{chapter,,,file name}
@ref{chapter,,,,manual}
@ref{node,cross ref name}
@ref{node,,title}
@ref{node,,,file name}
@ref{node,,,,manual}
@ref{chapter,cross ref name,title,}
@ref{chapter,cross ref name,,file name}
@ref{chapter,cross ref name,,,manual}
@ref{node,cross ref name,title,}
@ref{node,cross ref name,,file name}
@ref{node,cross ref name,,,manual}
@ref{chapter,cross ref name,title,file name}
@ref{chapter,cross ref name,title,,manual}
@ref{node,cross ref name,title,file name}
@ref{node,cross ref name,title,,manual}
@ref{chapter,cross ref name,title, file name, manual}
@ref{node,cross ref name,title, file name, manual}
@ref{chapter,,title,file name}
@ref{chapter,,title,,manual}
@ref{node,,title,file name}
@ref{node,,title,,manual}
@ref{chapter,,title, file name, manual}
@ref{node,,title, file name, manual}
@ref{chapter,,,file name,manual}
@ref{node,,,file name,manual}
@ref{,cross ref name,title,}
@ref{,cross ref name,,file name}
@ref{,cross ref name,,,manual}
@ref{,cross ref name,title,file name}
@ref{,cross ref name,title,,manual}
@ref{,cross ref name,title, file name, manual}
@ref{,,title,file name}
@ref{,,title,,manual}
@ref{,,title, file name, manual}
@ref{,,,file name,manual}

@inforef{chapter, cross ref name, file name}
@inforef{chapter}
@inforef{chapter, cross ref name}
@inforef{chapter,,file name}
@inforef{node, cross ref name, file name}
@inforef{node}
@inforef{node, cross ref name}
@inforef{node,,file name}
@inforef{,cross ref name }
@inforef{,,file name}
@inforef{,cross ref name, file name}

@table @bullet
@item a
line
@end table

@vtable @asis
@item a
line
@end vtable

@ftable @minus
@item a
line
@end ftable


@end macro

@mymacro{}

@example
@mymacro{}
@end example

@cindex truc
@cindex Truc
@cindex .
@cindex ?
@cindex a
@findex truc
@findex Truc
@findex .
@findex ?
@findex a


cp
@printindex cp

fn
@printindex fn

vr
@printindex vr

ky
@printindex ky

pg
@printindex pg

tp
@printindex tp



@node chapter
@chapter chapter

@footnote{in footnote}

@format
@menu 
* section:: section

Menu comment
``simple-double--three---four----''@*

@end menu
@end format

@node section
@section A section

@menu
* subsection:: 
@end menu

@node subsection
@subsection subsection

@menu
* subsubsection::
@end menu

@anchor{anchor}

@node subsubsection
@subsubsection subsubsection

@node chapter2
@chapter chapter 2

@printindex cp
@printindex fn

@contents
@shortcontents
