\input texinfo   @c -*-texinfo-*-
@comment %**start of header
@setfilename menus.info

@node Top
@top Top

@menu
* chapter::               chapter

Menu comment

* chapter2:description.   Chapter 2
@end menu

Text.

@menu
* (gcc):: text @table @minus
@item item
table line
@end table
@end menu

Some text.

@menu
* (manual):: desc
comment
* (info):: before verbatim @verbatim
some @ verb{' atim
* (texinfo):: in @ verbatim
@end verbatim
* (manual2):: $@html
<i></i>
@end html
Log$
* (truc):: @acronym{description
acronym}
@end menu
After menu

@menu
* (manual):: @table @asis
@item item
* (node)::
menu comment ?
* (node2):: description ?
  description continue ?
comment.
@end table
@end menu

@node chapter
@chapter chapter

@footnote{in footnote}

@format
@menu 
* s--ect@comma{}ion:: s--ect@comma{}ion

Menu comment
``simple-double--three---four----''@*

@end menu
@end format

@node s--ect@comma{}ion
@section A section

@menu
* subsection:: 
@end menu

@node subsection
@subsection subsection

@menu
@example
* subsubsection::
Menu comment

* a description:(manual) other manual node.   Chapter 2
@end example
@end menu

@anchor{anchor}

@node subsubsection
@subsubsection subsubsection

@node chapter2
@chapter chapter 2

@contents
@shortcontents

@bye
