\input texinfo @c -*-texinfo-*-

@setfilename quotes.info

@ifset utf8
@documentencoding utf-8
@set print_utf8 This is utf8.
@end ifset

@ignore 
rm -rf quotes quotes-utf8 quotes-utf8.* quotes.dvi quotes.info quotes.?? \
 quotes.toc quotes.log quotes.aux
~/src/texinfo/util/texi2dvi quotes.texi
cp quotes.dvi  quotes.dvi-save
~/src/texinfo/makeinfo/makeinfo quotes.texi
~/src/texinfo/makeinfo/makeinfo --html quotes.texi
~/src/texinfo/util/texi2dvi --texinfo='@set utf8' -o quotes-utf8.dvi quotes.texi
mv quotes.dvi-save quotes.dvi
~/src/texinfo/makeinfo/makeinfo -D utf8 quotes.texi -o quotes-utf8.info
~/src/texinfo/makeinfo/makeinfo -D utf8 --html quotes.texi -o quotes-utf8
@end ignore

@macro quotes
``simple-double--three---four----'' `simple' quotedblleft: @quotedblleft{} @*
code: @code{``simple-double--three---four----'' `simple' quotedblleft: @quotedblleft{}} @*
asis: @asis{``simple-double--three---four----'' `simple' quotedblleft: @quotedblleft{}} @*
strong: @strong{``simple-double--three---four----'' `simple' quotedblleft: @quotedblleft{}} @*
kbd: @kbd{``simple-double--three---four----'' `simple' quotedblleft: @quotedblleft{}} @*
samp: @samp{``simple-double--three---four----'' `simple' quotedblleft: @quotedblleft{}} @*
@end macro

@macro allquotes
@quotes

@example
@@set txicodequoteundirected
@@set txicodequotebacktick
@end example
@set txicodequoteundirected
@set txicodequotebacktick
@quotes

@example
@@clear txicodequoteundirected
@@clear txicodequotebacktick
@end example
@clear txicodequoteundirected
@clear txicodequotebacktick
@quotes
@end macro

@copying
@allquotes
@end copying
@titlepage
Titlepage
@insertcopying
@end titlepage


@node Top 
@top test quotes

@value{print_utf8}

@allquotes

@example
@allquotes
@end example

@bye
