\input texinfo @c -*-texinfo-*-

@setfilename value_in_pass0_macros.info

@node Top
@top value in index commands

@set cp cp
@set fn fn
@set syncodeindex_command @syncodeindex

@syncodeindex cp fn
@syncodeindex cp fn

@set en en
@set documentlanguage_command @documentlanguage

documentlanguage @documentlanguage  en   

documentlanguage on its line
@documentlanguage  en  
line following documentlanguage

@set truc truc

definedx truc
@defindex truc
after

@set trucindex_command @trucindex

@trucindex index truc

@set codeidx codeidx

@defcodeindex codeidx

@set defcodeindex_entry a @var{index entry} t@'e @^{@dotless{i}}

@codeidxindex a @var{index entry} t@'e @^{@dotless{i}}

@cindex cindex entry

@syncodeindex ky pg

@kindex truc kindex
@pindex pindex codeidx

@synindex truc cp

@defindex abc
@defindex defg

@synindex abc defg
@synindex defg ky

@defgindex defg index entry

@abcindex abc index entry

pg
@printindex pg

ky
@printindex ky

truc
@printindex truc

value truc
@printindex truc

cp
@printindex cp

value cp
@printindex cp

defg
@printindex defg

abc
@printindex abc

fn
@printindex fn

@bye
