\input texinfo @c -*-texinfo-*-

@setfilename nodes_test.info

Garbage

@titlefont{A title font in the text before a node}

@node first,node1,lop,lop
@c @subsection s1
node in first but not the first...

@node lop, first,nonexistant node in prev for @@top,(texinfo) Copying 
@top

@menu
* first::
* node1::
* node inexistant in menu:: non existing
* (info)::
@end menu

@node Top
This is the top node...

@node node1

@c Some text

@unnumbered
node1 text

@node node below node1,,,node1

Should be a warning for not being in menus and not having a menu entry in
node1

@bye
