
@SECTION_BUTTONS = ();

foreach my $direction (('Up', 'Forward', 'Back', 'Next',
                        'Prev', 'FastForward', 'FastBack', 'This', 'NodeUp',
                        'NodePrev', 'NodeNext', 'Following' ))

{
    my $direction_node = "node-".$direction;
    my $direction_href = "href-".$direction;
    my $direction_name = "name-".$direction;
    push @SECTION_BUTTONS, \"|", \$direction_node, \$Texi2HTML::NODE{$direction}, \$direction_href, \$Texi2HTML::HREF{$direction}, \$direction_name, \$Texi2HTML::NAME{$direction}, \"|";
}

@MISC_BUTTONS = @SECTION_BUTTONS;

1;
