\input texinfo @c -*-texinfo-*-

@setfilename index_in_item_line_vtable_printindex.info

@node Top
@top test index entries in @@item @@table 

@vtable @asis
@item @cindex index
@option{opt}
More text
@item @cindex 2 index
@option{nopt}
Even more
@end vtable

@vindex another index

@printindex vr

@printindex cp

@bye
